### ISSUE TITLE
ダミーデータの生成機能

### ISSUE THREAD

**Issue by nanasess** [ec-cube2/cli#4]
2系の E2Eテストを実施する際、ダミーデータの生成をしています。
https://github.com/EC-CUBE/ec-cube2/blob/master/ctests/acceptance/_bootstrap.php
https://github.com/EC-CUBE/ec-cube2/blob/master/tests/class/fixtures/FixtureGenerator.php

4系の `bin/console eccube:fixtures:generate` コマンドのように、 cli インターフェイスを用意したいと思っているのですが、本 cli に取り込むことはポリシー的に大丈夫でしょうか？

**Comment by ttsuru** [comment]
@nanasess 
もちろん問題ありません！
今commandのロード関係をリファクタリングしてるのでその後にPRを作っていただけると助かります。

**Comment by ttsuru** [comment]
@nanasess 

ご連絡遅くなりました。
CLI 1.3.0 を追加し、`Application::appendConfigPath` というメソッドを追加しています。
`services.yaml` をいい感じにおいていただいて、 `composer.json` の `files` で自動的に読み込むことを想定しています。
https://getcomposer.org/doc/04-schema.md#files

**Comment by nanasess** [comment]
@ttsuru ありがとうございます。試してみます！

**Comment by ttsuru** [comment]
@nanasess 

まだ使い勝手も検証していないですが多分コマンドの追加だけであれば簡単にできるようになっていると思います。
`symfony/console` の遅延読み込みなので、cli自体も軽くなっていると思います。

通常のEC-CUBEプラグインからも読み込めるようにはしています。
フックポイント `Eccube2_Console_Application::__construct` です。

**Comment by nanasess** [comment]
`eccube:fixtures:generate` でダミーデータを生成できるようにしてみました
https://github.com/nanasess/eccube2-fixture-generator

@ttsuru `Application::appendConfigPath` で簡単にコマンドを追加できました。
こちらはクローズしたいと思います
